// Assemble matching/SPEC.md from the per-page sections in spec-sections/.
//
//   node matching/build-spec.mjs
//
// SPEC.md is the Phase 1 deliverable and the thing matching/gate.sh preflights
// against, so it is GENERATED rather than hand-maintained: edit the section
// file, rebuild. The page list comes from matching/harness.mjs (the same
// reader gate.sh's `--table` loop uses) and the heading test from its
// specHeadingRe, whose pattern is has_spec's grep verbatim — so a section can
// no longer build fine here and then re-block its own page at the gate.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
// DIR too: harness.mjs resolves it with fileURLToPath, and the URL#pathname
// form this file used percent-encodes a space in the checkout path (#47).
import { DIR, PAGES, specHeadingRe } from "./harness.mjs";

const SECTIONS = join(DIR, "spec-sections");

// Order = live's nav order, then the detail templates. Both fall out of the
// table's own order within each group, so this is not a second list to keep.
const KEYS = [
  ...PAGES.filter((p) => p.group === "nav"),
  ...PAGES.filter((p) => p.group !== "nav"),
].map((p) => p.spec ?? p.key);

const parts = [];
const missing = [];

const chrome = join(SECTIONS, "_chrome.md");
if (existsSync(chrome)) parts.push(readFileSync(chrome, "utf8").trim());
else missing.push("_chrome");

for (const page of KEYS) {
  const file = join(SECTIONS, `${page}.md`);
  if (!existsSync(file)) {
    missing.push(page);
    continue;
  }
  const body = readFileSync(file, "utf8").trim();
  // The preflight greps `^##+ +<page>`; a section that does not open with its
  // own key would build fine here and then refuse at the gate, which is the
  // most confusing possible failure. Catch it now.
  if (!specHeadingRe(page).test(body)) {
    console.error(
      `WARNING: ${page}.md does not open with a '## ${page}' heading — gate.sh will still refuse this page.`,
    );
  }
  parts.push(body);
}

// The header is a spec-section like any other, so a site can say what a
// citation looks like there and what its own ladders are. DEFAULT_HEADER is
// what a site gets before it writes one: the two paragraphs that are true of
// every project, and nothing that is not.
const DEFAULT_HEADER = `# Reference spec

GENERATED by \`node matching/build-spec.mjs\` from \`matching/spec-sections/\`.
Edit the section files, not this one.

This is the Phase 1 deliverable of the \`matching-a-page\` skill and the
precondition \`matching/gate.sh\` enforces: a page with no section here does not
get a geometry round (see the matching rules in CLAUDE.md).

`;
const headerFile = join(SECTIONS, "_header.md");
const header = existsSync(headerFile)
  ? readFileSync(headerFile, "utf8").trimEnd() + "\n\n"
  : DEFAULT_HEADER;

writeFileSync(join(DIR, "SPEC.md"), header + parts.join("\n\n---\n\n") + "\n");

const built = KEYS.length - missing.filter((m) => m !== "_chrome").length;
console.log(
  `SPEC.md built — ${built}/${KEYS.length} pages${missing.length ? `, MISSING: ${missing.join(", ")}` : ""}`,
);
process.exit(missing.length ? 1 : 0);
