// Code generated by Prismic. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import AnchorIntro from "./AnchorIntro/index.svelte";
import CtaBanner from "./CtaBanner/index.svelte";
import FeaturedProjects from "./FeaturedProjects/index.svelte";
import Hero from "./Hero/index.svelte";
import ImageCards from "./ImageCards/index.svelte";
import LeadText from "./LeadText/index.svelte";
import LetsTalk from "./LetsTalk/index.svelte";
import MediaText from "./MediaText/index.svelte";
import PageHero from "./PageHero/index.svelte";
import ProcessSteps from "./ProcessSteps/index.svelte";
import ProjectList from "./ProjectList/index.svelte";
import QuoteBanner from "./QuoteBanner/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";
import Statement from "./Statement/index.svelte";
import TeamContacts from "./TeamContacts/index.svelte";
import Testimonial from "./Testimonial/index.svelte";
import TextColumns from "./TextColumns/index.svelte";
import Timeline from "./Timeline/index.svelte";

export const components = {
	accordion: Accordion,
	anchor_intro: AnchorIntro,
	cta_banner: CtaBanner,
	featured_projects: FeaturedProjects,
	hero: Hero,
	image_cards: ImageCards,
	lead_text: LeadText,
	lets_talk: LetsTalk,
	media_text: MediaText,
	page_hero: PageHero,
	process_steps: ProcessSteps,
	project_list: ProjectList,
	quote_banner: QuoteBanner,
	rich_text: RichText,
	section_grid: SectionGrid,
	statement: Statement,
	team_contacts: TeamContacts,
	testimonial: Testimonial,
	text_columns: TextColumns,
	timeline: Timeline
};