// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | LeadTextSlice
  | TextColumnsSlice
  | AccordionSlice
  | RichTextSlice
  | HeroSlice
  | MediaTextSlice
  | SectionGridSlice
  | TestimonialSlice
  | CtaBannerSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *Accordion → Default → Primary → items*
 */
export interface AccordionSliceDefaultPrimaryItemsItem {
  /**
   * title field in *Accordion → Default → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. About the project
   * - **API ID Path**: accordion.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * body field in *Accordion → Default → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;
}

/**
 * Primary content in *Accordion → Default → Primary*
 */
export interface AccordionSliceDefaultPrimary {
  /**
   * items field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<AccordionSliceDefaultPrimaryItemsItem>>;

  /**
   * allowMultiple field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: accordion.default.primary.allowMultiple
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  allowMultiple: prismic.BooleanField;
}

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: A list of collapsible disclosure items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault;

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Accordion
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSlice = prismic.SharedSlice<
  "accordion",
  AccordionSliceVariation
>;

/**
 * Primary content in *CtaBanner → Default → Primary*
 */
export interface CtaBannerSliceDefaultPrimary {
  /**
   * heading field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g. Ready to start your project?
   * - **API ID Path**: cta_banner.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * buttonLabel field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Talk with us
   * - **API ID Path**: cta_banner.default.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * buttonLink field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * background (theme token) field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: light
   * - **API ID Path**: cta_banner.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<"light" | "dark" | "white", "filled">;
}

/**
 * Default variation for CtaBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Full-bleed band with a headline and one call-to-action link
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaBanner*
 */
type CtaBannerSliceVariation = CtaBannerSliceDefault;

/**
 * CtaBanner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: CtaBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSlice = prismic.SharedSlice<
  "cta_banner",
  CtaBannerSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * background_image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * cta_label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * cta_link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Background image with heading, body, and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Full-bleed hero with background media and heading/CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *LeadText → Default → Primary*
 */
export interface LeadTextSliceDefaultPrimary {
  /**
   * eyebrow field in *LeadText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. The Challenge
   * - **API ID Path**: lead_text.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * body field in *LeadText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lead_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for LeadText Slice
 *
 * - **API ID**: `default`
 * - **Description**: An eyebrow label above a lead paragraph
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LeadTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LeadTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LeadText*
 */
type LeadTextSliceVariation = LeadTextSliceDefault;

/**
 * LeadText Shared Slice
 *
 * - **API ID**: `lead_text`
 * - **Description**: LeadText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LeadTextSlice = prismic.SharedSlice<
  "lead_text",
  LeadTextSliceVariation
>;

/**
 * Primary content in *MediaText → Image Right → Primary*
 */
export interface MediaTextSliceImageRightPrimary {
  /**
   * heading field in *MediaText → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.imageRight.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *MediaText → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.imageRight.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * media field in *MediaText → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.imageRight.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  media: prismic.ImageField<never>;
}

/**
 * Image Right variation for MediaText Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Media on the right, text on the left
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaTextSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<MediaTextSliceImageRightPrimary>,
  never
>;

/**
 * Primary content in *MediaText → Image Left → Primary*
 */
export interface MediaTextSliceImageLeftPrimary {
  /**
   * heading field in *MediaText → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.imageLeft.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *MediaText → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.imageLeft.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * media field in *MediaText → Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.imageLeft.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  media: prismic.ImageField<never>;
}

/**
 * Image Left variation for MediaText Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Media on the left, text on the right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaTextSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<MediaTextSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *MediaText*
 */
type MediaTextSliceVariation =
  MediaTextSliceImageRight | MediaTextSliceImageLeft;

/**
 * MediaText Shared Slice
 *
 * - **API ID**: `media_text`
 * - **Description**: Image/video beside rich text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaTextSlice = prismic.SharedSlice<
  "media_text",
  MediaTextSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SectionGrid → Default → Primary*
 */
export interface SectionGridSliceDefaultPrimary {
  /**
   * heading field in *SectionGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * columns field in *SectionGrid → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 3
   * - **API ID Path**: section_grid.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;
}

/**
 * Primary content in *SectionGrid → Items*
 */
export interface SectionGridSliceDefaultItem {
  /**
   * item_heading field in *SectionGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_grid.items[].item_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_heading: prismic.RichTextField;

  /**
   * item_body field in *SectionGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_grid.items[].item_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_body: prismic.RichTextField;

  /**
   * item_media field in *SectionGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_grid.items[].item_media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  item_media: prismic.ImageField<never>;

  /**
   * item_link field in *SectionGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section_grid.items[].item_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  item_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SectionGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Heading plus a grid of item cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionGridSliceDefaultPrimary>,
  Simplify<SectionGridSliceDefaultItem>
>;

/**
 * Slice variation for *SectionGrid*
 */
type SectionGridSliceVariation = SectionGridSliceDefault;

/**
 * SectionGrid Shared Slice
 *
 * - **API ID**: `section_grid`
 * - **Description**: N-column grid of card items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionGridSlice = prismic.SharedSlice<
  "section_grid",
  SectionGridSliceVariation
>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * label field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. What clients are saying
   * - **API ID Path**: testimonial.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * quote field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Quote text WITHOUT the “ ” marks — the component draws them
   * - **API ID Path**: testimonial.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote: prismic.KeyTextField;

  /**
   * name field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Dana Whitfield
   * - **API ID Path**: testimonial.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * role field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Director of Operations, Northgate
   * - **API ID Path**: testimonial.default.primary.role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * avatar field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: An attributed pull quote with an optional avatar/name/role credit
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Item in *TextColumns → Default → Primary → columns*
 */
export interface TextColumnsSliceDefaultPrimaryColumnsItem {
  /**
   * title field in *TextColumns → Default → Primary → columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_columns.default.primary.columns[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * body field in *TextColumns → Default → Primary → columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_columns.default.primary.columns[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *TextColumns → Default → Primary*
 */
export interface TextColumnsSliceDefaultPrimary {
  /**
   * eyebrow field in *TextColumns → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Our Solution
   * - **API ID Path**: text_columns.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * hasTopRule field in *TextColumns → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: text_columns.default.primary.hasTopRule
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hasTopRule: prismic.BooleanField;

  /**
   * desktopColumns field in *TextColumns → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 3
   * - **API ID Path**: text_columns.default.primary.desktopColumns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  desktopColumns: prismic.SelectField<"2" | "3" | "4", "filled">;

  /**
   * columns field in *TextColumns → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_columns.default.primary.columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  columns: prismic.GroupField<
    Simplify<TextColumnsSliceDefaultPrimaryColumnsItem>
  >;
}

/**
 * Default variation for TextColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: An eyebrow, an optional rule, and a row of text columns
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextColumnsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextColumns*
 */
type TextColumnsSliceVariation = TextColumnsSliceDefault;

/**
 * TextColumns Shared Slice
 *
 * - **API ID**: `text_columns`
 * - **Description**: TextColumns
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnsSlice = prismic.SharedSlice<
  "text_columns",
  TextColumnsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionSlice,
      AccordionSliceDefaultPrimaryItemsItem,
      AccordionSliceDefaultPrimary,
      AccordionSliceVariation,
      AccordionSliceDefault,
      CtaBannerSlice,
      CtaBannerSliceDefaultPrimary,
      CtaBannerSliceVariation,
      CtaBannerSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LeadTextSlice,
      LeadTextSliceDefaultPrimary,
      LeadTextSliceVariation,
      LeadTextSliceDefault,
      MediaTextSlice,
      MediaTextSliceImageRightPrimary,
      MediaTextSliceImageLeftPrimary,
      MediaTextSliceVariation,
      MediaTextSliceImageRight,
      MediaTextSliceImageLeft,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SectionGridSlice,
      SectionGridSliceDefaultPrimary,
      SectionGridSliceDefaultItem,
      SectionGridSliceVariation,
      SectionGridSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      TextColumnsSlice,
      TextColumnsSliceDefaultPrimaryColumnsItem,
      TextColumnsSliceDefaultPrimary,
      TextColumnsSliceVariation,
      TextColumnsSliceDefault,
    };
  }
}
